### ISSUE TITLE
遇到点小问题，想请教一下你，

### ISSUE THREAD

**Issue by ELEVENEV** [ChenYXin/TakePicAndGallery#1]
大佬，如果你方便的话，可以提供一下你的qq，我加一下你，请教你几个问题。或者你加我也可以，（1836777832）

**Comment by Donkor798** [comment]
qq：1224670105




| |
donkor
邮箱：donkor@yeah.net
|

签名由 网易邮箱大师 定制

在2018年03月27日 21:24，王学宏 写道：

大佬，如果你方便的话，可以提供一下你的qq，我加一下你，请教你几个问题。或者你加我也可以，（1836777832）
